require("teebowie.core.plugins")
require("teebowie.core.utils")
require("teebowie.core.colorscheme")
require("teebowie.plugins.devicons")

require("teebowie.core.options")
require("teebowie.core.keymaps")
require("teebowie.core.autocommands")

require("teebowie.plugins.cmp")
require("teebowie.plugins.telescope")
require("teebowie.plugins.lsp")
require("teebowie.plugins.treesitter")
require("teebowie.plugins.nvimtree")
require("teebowie.plugins.autopairs")
require("teebowie.plugins.comment")
require("teebowie.plugins.bufferline")
require("teebowie.plugins.nvim-surround")
require("teebowie.plugins.lualine")
require("teebowie.plugins.alpha")
require("teebowie.plugins.todo-comments")
require("teebowie.plugins.colorizer")
require("teebowie.plugins.indent")
require("teebowie.plugins.session-manager")
require("teebowie.plugins.dressing")
require("teebowie.plugins.shade")
